---

- name: reload systemd for grok_exporter
  become: true
  systemd:
    daemon_reload: true

- name: restart grok_exporter
  become: true
  systemd:
    name: grok_exporter.service
    state: restarted
